name: on_push

on:
  push:
    branch:
      - "**" # This will run on all branches, and must be quoted to be handled by yaml
    schedule:
      - cron: '0 0 * * 6' #This will run at 0:00 on Saturday: https://crontab.guru. Adjust the cron for scheduled test runs

jobs:
#runs-on will need to be modified to an on-prem server, windows or linux.
  build_and_test:
    runs-on: ubuntu-latest

    env:
      RUNNER_OS: true
      HEADLESS_CHROME: true

    steps:
      - name: Set start time
        run: echo "START_TIME=$(date +%s)" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 16
      - name: Run tests with maven
        working-directory: webdriver_java
        run: mvn test
      - name: Collect build data
        working-directory: webdriver_java
        if: always()
        run: |
          echo "TOTAL_DURATION=$(expr $(date +%s) - ${START_TIME})"
          ./resources/test_result_script.sh